version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "**/*"
    schedule:
      interval: daily
    ignore:
      - dependency-name: dotnet/sdk
        update-types: ["version-update:semver-major"]
    groups:
      all-docker:
        patterns:
          - "*"
  - package-ecosystem: docker-compose
    directories:
      - "**/*"
    schedule:
      interval: daily
    ignore:
      - dependency-name: localhost
    groups:
      all-docker-compose:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directories:
      - /
      - "**/*"
    schedule:
      interval: daily
    groups:
      all-github-actions:
        patterns:
          - "*"
