name: Build and publish NuGet package through the repos devcontainer
description: Builds and publishes a NuGet package to the package registry.

inputs:
  nugetAuthToken:
    description: The NuGet authentication token to use when pushing the package.
    required: true
  projectFile:
    description: The project file to package such as MyProject/MyProject.csproj. Include the relative path from the root of the repository if necessary.
    required: true
  version:
    description: The semantic version to apply such as 1.0.0 or 1.0.0-alpha2+a12b345.
    required: true
  packageRepository:
    description: The URL of the NuGet package repository to push to.
    required: false
    default: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
  projectDirectory:
    description: The directory containing the project to be packaged relative to repository root. Defaults to ./
    required: false
    default: ./
  registryHost:
    description: The host of the container registry to pull devcontainers from. If not provided, no login will be performed.
    required: false
    default: ''
  registryUsername:
    description: The username to use to authenticate with the container registry for pulling devcontainers. If not provided, no login will be performed.
    required: false
    default: ''
  registryPassword:
    description: The token to use to authenticate with the container registry for pulling devcontainers. If not provided, no login will be performed.
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      if: inputs.registryHost != '' && inputs.registryUsername != '' && inputs.registryPassword != ''
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registryHost }}
        username: ${{ inputs.registryUsername }}
        password: ${{ inputs.registryPassword }}

    - name: Create .env for build
      shell: bash
      run: |
        mkdir -p ./.devcontainer
        touch ./.devcontainer/.env

    - name: dotnet pack Release
      if: github.ref_type == 'branch'
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          source "${{ github.action_path }}/publish-nuget.sh"
        push: never
        env: |
          PROJECT_FILE=${{ inputs.projectFile }}
          VERSION=${{ inputs.version }}
          PACKAGE_REPOSITORY=${{ inputs.packageRepository }}
          NUGET_TOKEN=${{ inputs.nugetAuthToken }}
