name: Build

on: [push, workflow_dispatch]

jobs:
  run-tests:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@v0.2.2

      - name: Create .env for build
        shell: bash
        run: |
          cat > ./.devcontainer/.env <<EOF
          EOF

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            bats --print-output-on-failure --report-formatter junit ./tests/
          push: never

      - name: Add test report title
        if: always()
        run: |
          echo "# Test Results" >> $GITHUB_STEP_SUMMARY

      - name: Generate test report
        uses: dorny/test-reporter@v2.0.0
        if: always()
        with:
          name: Test Results
          path: report.xml
          reporter: java-junit

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@v0.2.2
        with:
          version: ${{ steps.version.outputs.version }}
