name: Build

on: [push, workflow_dispatch]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - id: version
        name: Get semantic version
        uses: spritely/actions.semantic-version/get@v0.2.2

      - name: Create .env for build
        shell: bash
        run: |
          cat > ./.devcontainer/.env <<EOF
          EOF

      - name: Run tests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            mkdir -p test-reports
            bats --version
            bats --print-output-on-failure --report-formatter junit --output ./test-reports/ ./tests/
          push: never

      - id: setup-tests
        name: Setup test container registry and NuGet server
        run: |
          docker run -d -p 5000:5000 \
              -v ${{ github.workspace }}/tests/auth:/auth \
              -e REGISTRY_AUTH=htpasswd \
              -e REGISTRY_AUTH_HTPASSWD_REALM="Registry Realm" \
              -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
              --name registry registry:2
          
          docker run -d -p 5001:80 \
              -e ApiKey=fake-token \
              --name baget loicsharma/baget:0.4.0-preview2

      - name: Run test - Publish NuGet publishes expected package
        uses: ./tests/basic-test
        if: always() && steps.setup-tests.outcome == 'success'

      - name: Add test report title
        if: always()
        run: |
          echo "# Test Results" >> $GITHUB_STEP_SUMMARY

      - name: Generate test report
        uses: dorny/test-reporter@v2.0.0
        if: always()
        with:
          name: Test Results
          path: test-results/*.xml
          reporter: java-junit

      - name: Apply semantic version
        if: ${{ steps.version.outputs.branchName == github.event.repository.default_branch }}
        uses: spritely/actions.semantic-version/apply@v0.2.2
        with:
          version: ${{ steps.version.outputs.version }}
